# Generated by Django 4.2.23 on 2025-11-05 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='stock_updated_manually',
            field=models.BooleanField(default=False, verbose_name='Stock actualizado manualmente'),
        ),
    ]
