# Generated by Django 4.2.23 on 2025-11-11 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document_upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttype',
            name='id_type',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id_document', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Título descriptivo del documento', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción opcional del documento')),
                ('file', models.FileField(help_text='Archivo a subir', upload_to='documents/%Y/%m/%d/')),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True)),
                ('file_type', models.CharField(blank=True, help_text='Tipo MIME del archivo', max_length=100, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report_type', models.ForeignKey(blank=True, help_text='Tipo de reporte relacionado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='document_upload.reporttype')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uploaded_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
