# Generated by Django 4.2.23 on 2025-11-11 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document_upload', '0002_alter_reporttype_id_type_uploadeddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'document_types',
            },
        ),
        migrations.RemoveField(
            model_name='uploadeddocument',
            name='report_type',
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='document_type',
            field=models.ForeignKey(blank=True, help_text='Tipo de documento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='document_upload.documenttype'),
        ),
    ]
