# Generated by Django 4.2.23 on 2025-11-05 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0036_auto_20251103_0042'),
        ('repuestos', '0002_purchaseorder_stock_updated_manually'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='stock_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='stock_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_updated_purchase_orders', to='documents.flotauser'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='stock_updated_manually',
            field=models.BooleanField(default=False),
        ),
    ]
