# Generated by Django 4.2.25 on 2025-10-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_ingreso_exit_registered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
