# Generated by Django 4.2.25 on 2025-10-19 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_maintenanceschedule_end_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingresos', to='documents.maintenanceschedule'),
        ),
    ]
