# Generated by Django 4.2.25 on 2025-10-23 00:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0015_flotauser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flotauser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flotauser', to=settings.AUTH_USER_MODEL),
        ),
    ]
