# Generated by Django 4.2.23 on 2025-10-27 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_maintenanceschedule_related_incidents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceschedule',
            name='recurrence_rule',
        ),
        migrations.RemoveField(
            model_name='maintenanceschedule',
            name='reminder_minutes',
        ),
        migrations.RemoveField(
            model_name='maintenanceschedule',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='maintenanceschedule',
            name='supervisor',
        ),
    ]
