# Generated by Django 4.2.23 on 2025-10-27 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_remove_maintenanceschedule_recurrence_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='related_ingreso',
            field=models.ForeignKey(blank=True, db_column='related_ingreso_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='documents.ingreso'),
        ),
    ]
