# Generated by Django 4.2.23 on 2025-10-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_incident_related_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoimage',
            name='description',
            field=models.CharField(blank=True, help_text='Descripción del tipo de foto (ej. "Estado frontal", "Daño en neumático")', max_length=200, null=True),
        ),
    ]
