# Generated by Django 4.2.23 on 2025-10-29 16:01

from django.db import migrations


def migrate_incident_to_incidents(apps, schema_editor):
    """Migrar datos del campo incident al campo incidents ManyToMany"""
    Diagnostics = apps.get_model('documents', 'Diagnostics')
    
    for diagnostic in Diagnostics.objects.filter(incident__isnull=False):
        diagnostic.incidents.add(diagnostic.incident)


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_add_diagnostics_incidents_manytomany'),
    ]

    operations = [
        migrations.RunPython(migrate_incident_to_incidents),
    ]
