# Generated by Django 4.2.23 on 2025-11-02 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0032_remove_route_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='ingreso',
            field=models.OneToOneField(blank=True, db_column='ingreso_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.ingreso'),
        ),
    ]
