# Generated by Django 4.2.23 on 2025-11-02 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0033_alter_workorder_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='ingreso',
            field=models.ForeignKey(blank=True, db_column='ingreso_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='documents.ingreso'),
        ),
    ]
