# Generated by Django 4.2.23 on 2025-11-03 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0034_alter_workorder_ingreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderImage',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, help_text='Descripción del tipo de foto (ej. "Trabajo realizado", "Estado final")', max_length=200, null=True)),
                ('image', models.ImageField(upload_to='work_order_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='uploaded_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_work_order_images', to='documents.flotauser')),
                ('work_order', models.ForeignKey(db_column='work_order_id', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='documents.workorder')),
            ],
            options={
                'db_table': 'WorkOrderImages',
            },
        ),
    ]
