# Generated by Django 4.2.23 on 2025-11-06 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pausas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderpause',
            name='is_personal_pause',
            field=models.BooleanField(default=False),
        ),
    ]
