# Generated by Django 4.2.23 on 2025-11-11 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id_type', models.AutoField(primary_key=True)),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'report_types',
            },
        ),
    ]
