# Generated by Django 4.2.25 on 2025-10-19 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='exit_registered_by',
            field=models.ForeignKey(blank=True, db_column='exit_registered_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_registered_ingresos', to='documents.flotauser'),
        ),
    ]
