# Generated by Django 4.2.23 on 2025-10-19 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_maintenanceschedule_expected_chofer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='service_type',
            field=models.ForeignKey(blank=True, db_column='service_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.servicetype'),
        ),
    ]
