# Generated by Django 4.2.23 on 2025-10-19 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_maintenanceschedule_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='entry_registered_by',
            field=models.ForeignKey(blank=True, db_column='entry_registered_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_registered_ingresos', to='documents.flotauser'),
        ),
    ]
