# Generated by Django 4.2.23 on 2025-10-21 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_ingreso_entry_registered_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='service_type',
            field=models.ForeignKey(blank=True, db_column='service_type_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.servicetype'),
        ),
    ]
