# Generated by Django 4.2.23 on 2025-10-21 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_ingreso_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id_work_order', models.AutoField(primary_key=True, serialize=False)),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('actual_completion', models.DateTimeField(blank=True, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to='documents.flotauser')),
                ('ingreso', models.OneToOneField(db_column='ingreso_id', on_delete=django.db.models.deletion.CASCADE, related_name='work_order', to='documents.ingreso')),
            ],
            options={
                'db_table': 'WorkOrders',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderStatus',
            fields=[
                ('id_status', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#6c757d', max_length=7)),
            ],
            options={
                'db_table': 'WorkOrderStatuses',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderMechanic',
            fields=[
                ('id_assignment', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_datetime', models.DateTimeField(auto_now_add=True)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('mechanic', models.ForeignKey(db_column='mechanic_id', on_delete=django.db.models.deletion.CASCADE, related_name='work_order_assignments', to='documents.flotauser')),
                ('work_order', models.ForeignKey(db_column='work_order_id', on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_assignments', to='documents.workorder')),
            ],
            options={
                'db_table': 'WorkOrderMechanics',
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='status',
            field=models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, to='documents.workorderstatus'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='supervisor',
            field=models.ForeignKey(blank=True, db_column='supervisor_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_work_orders', to='documents.flotauser'),
        ),
        migrations.CreateModel(
            name='SparePartUsage',
            fields=[
                ('id_usage', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_used', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('used_datetime', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('repuesto', models.ForeignKey(db_column='repuesto_id', on_delete=django.db.models.deletion.CASCADE, to='documents.repuesto')),
                ('work_order', models.ForeignKey(db_column='work_order_id', on_delete=django.db.models.deletion.CASCADE, related_name='spare_part_usages', to='documents.workorder')),
            ],
            options={
                'db_table': 'SparePartUsages',
            },
        ),
    ]
