# Generated by Django 4.2.23 on 2025-10-21 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_workorder_workorderstatus_workordermechanic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingreso',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='ingreso',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='task',
            name='ingreso',
        ),
        migrations.AddField(
            model_name='task',
            name='work_order',
            field=models.ForeignKey(blank=True, db_column='work_order_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.workorder'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='service_type',
            field=models.ForeignKey(blank=True, db_column='service_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.servicetype'),
        ),
        migrations.AlterField(
            model_name='task',
            name='service_type',
            field=models.ForeignKey(blank=True, db_column='service_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.servicetype'),
        ),
    ]
