# Generated by Django 4.2.25 on 2025-10-22 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_ingresoimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, db_column='uploaded_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_ingreso_images', to='documents.flotauser'),
        ),
    ]
