# Generated by Django 4.2.23 on 2025-10-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_alter_flotauser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(blank=True, choices=[('Seguridad', 'Seguridad'), ('Operativo', 'Operativo'), ('Mantenimiento', 'Mantenimiento')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='priority',
            field=models.CharField(blank=True, choices=[('Baja', 'Baja'), ('Normal', 'Normal'), ('Alta', 'Alta'), ('Urgente', 'Urgente')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='severity',
            field=models.CharField(blank=True, choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Critica', 'Crítica')], max_length=20, null=True),
        ),
    ]
