# Generated by Django 4.2.23 on 2025-10-25 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_alter_incident_category_alter_incident_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenanceschedule',
            name='end_datetime',
        ),
    ]
