# Generated by Django 4.2.23 on 2025-10-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_alter_diagnostics_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostics',
            name='status',
            field=models.CharField(choices=[('Reportada', 'Reportada'), ('Diagnostico_In_Situ', 'Diagnóstico In Situ'), ('OT_Generada', 'OT Generada'), ('Resuelta', 'Resuelta')], default='Reportada', max_length=30),
        ),
    ]
