# Generated by Django 4.2.23 on 2025-10-27 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_alter_diagnostics_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='related_incidents',
            field=models.ManyToManyField(blank=True, help_text='Incidentes asociados a esta agenda de mantenimiento', related_name='maintenance_schedules', to='documents.incident'),
        ),
    ]
