# Generated by Django 4.2.23 on 2025-10-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0026_ingresoimage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingreso',
            name='es_ingreso_tecnico',
            field=models.BooleanField(default=False, verbose_name='Es ingreso técnico'),
        ),
    ]
