# Generated by Django 4.2.23 on 2025-10-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_add_diagnostics_incidents_manytomany'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostics',
            name='location',
            field=models.CharField(blank=True, help_text='Ubicación donde se realizó el diagnóstico (para diagnósticos in situ)', max_length=200, null=True),
        ),
    ]
