# Generated by Django 4.2.23 on 2025-10-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_remove_route_truck_route_vehicles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='driver',
        ),
    ]
