# Generated by Django 4.2.23 on 2025-10-19 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_ingreso_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='expected_chofer',
            field=models.ForeignKey(blank=True, db_column='expected_chofer_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expected_ingresos', to='documents.flotauser'),
        ),
    ]
