# Generated by Django 4.2.25 on 2025-10-22 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_remove_ingreso_service_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleStatusImage',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='vehicle_status_images/')),
                ('vehicle_status', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_images', to='documents.vehiclestatus')),
            ],
            options={
                'db_table': 'VehicleStatusImages',
            },
        ),
    ]
