# Generated by Django 4.2.25 on 2025-10-26 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_remove_maintenanceschedule_end_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='affects_operation',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='auto_resolved',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='category',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='estimated_resolution_time',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='follow_up_required',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='possible_cause',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='related_ingreso',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='related_schedule',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='related_work_order',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='resolution_notes',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='resolution_source',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='resolution_type',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='resolved_at',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='route',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='severity',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='status',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='symptoms',
        ),
        migrations.CreateModel(
            name='IncidentDiagnostics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(blank=True, choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta'), ('Critica', 'Crítica')], max_length=20, null=True)),
                ('category', models.CharField(blank=True, choices=[('Seguridad', 'Seguridad'), ('Operativo', 'Operativo'), ('Mantenimiento', 'Mantenimiento')], max_length=50, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('possible_cause', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Reportada', 'Reportada'), ('En_revision', 'En revisión'), ('Resuelta', 'Resuelta'), ('Cerrada', 'Cerrada')], default='Reportada', max_length=30)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('estimated_resolution_time', models.CharField(blank=True, max_length=50, null=True)),
                ('resolution_type', models.CharField(blank=True, choices=[('Taller', 'Taller'), ('Campo', 'Campo'), ('No_aplica', 'No aplica')], max_length=50, null=True)),
                ('auto_resolved', models.BooleanField(default=False)),
                ('resolution_source', models.CharField(blank=True, choices=[('OT_Completada', 'OT Completada'), ('Ingreso_Cerrado', 'Ingreso Cerrado'), ('Manual', 'Manual')], max_length=50, null=True)),
                ('affects_operation', models.BooleanField(default=False)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('diagnostic_started_at', models.DateTimeField(blank=True, null=True)),
                ('diagnostic_completed_at', models.DateTimeField(blank=True, null=True)),
                ('diagnostic_method', models.CharField(blank=True, choices=[('Visual', 'Visual'), ('Instrumentos', 'Con Instrumentos'), ('Prueba', 'Prueba de Funcionamiento'), ('Otro', 'Otro')], max_length=50, null=True)),
                ('parts_needed', models.TextField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('photos_taken', models.BooleanField(default=False)),
                ('requires_specialist', models.BooleanField(default=False)),
                ('environmental_conditions', models.CharField(blank=True, max_length=200, null=True)),
                ('diagnostics_created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnostics_updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, db_column='assigned_to_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incident_diagnostics', to='documents.flotauser')),
                ('diagnostic_by', models.ForeignKey(blank=True, db_column='diagnostic_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosed_incidents', to='documents.flotauser')),
                ('diagnostics_created_by', models.ForeignKey(blank=True, db_column='diagnostics_created_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_incident_diagnostics', to='documents.flotauser')),
                ('diagnostics_updated_by', models.ForeignKey(blank=True, db_column='diagnostics_updated_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_incident_diagnostics', to='documents.flotauser')),
                ('incident', models.OneToOneField(db_column='incident_id', on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='documents.incident')),
                ('related_ingreso', models.ForeignKey(blank=True, db_column='related_ingreso_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_diagnostics', to='documents.ingreso')),
                ('related_schedule', models.ForeignKey(blank=True, db_column='related_schedule_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_diagnostics', to='documents.maintenanceschedule')),
                ('related_work_order', models.ForeignKey(blank=True, db_column='related_work_order_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_diagnostics', to='documents.workorder')),
                ('route', models.ForeignKey(blank=True, db_column='route_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_diagnostics', to='documents.route')),
            ],
            options={
                'db_table': 'IncidentDiagnostics',
            },
        ),
    ]
