# Generated by Django 4.2.23 on 2025-10-26 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_diagnostics_delete_incidentdiagnostics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostics',
            name='incident',
            field=models.ForeignKey(blank=True, db_column='incident_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics', to='documents.incident'),
        ),
    ]
