# Generated by Django 4.2.23 on 2025-10-29 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_ingreso_es_ingreso_tecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostics',
            name='incidents',
            field=models.ManyToManyField(blank=True, db_column='incident_ids', help_text='Incidentes asociados a este diagnóstico', related_name='diagnostics', to='documents.incident'),
        ),
        migrations.AlterField(
            model_name='diagnostics',
            name='incident',
            field=models.ForeignKey(blank=True, db_column='incident_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legacy_diagnostics', to='documents.incident'),
        ),
    ]
