# Generated by Django 4.2.25 on 2025-10-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_diagnostics_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='truck',
        ),
        migrations.AddField(
            model_name='route',
            name='vehicles',
            field=models.ManyToManyField(blank=True, db_column='route_vehicles', help_text='Vehículos asociados a esta ruta', related_name='routes', to='documents.vehicle'),
        ),
    ]
