# Generated by Django 4.2.23 on 2025-11-03 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0035_workorderimage'),
    ]

    operations = [
    ]
