# Generated by Django 4.2.23 on 2025-11-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0036_auto_20251103_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='parts_issued',
            field=models.BooleanField(default=False, help_text='Indica si se han registrado las salidas de repuestos para esta OT'),
        ),
    ]
