# Generated by Django 4.2.23 on 2025-11-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0037_workorder_parts_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='work_started_at',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se inició el trabajo', null=True),
        ),
    ]
