# Generated by Django 4.2.23 on 2025-11-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0038_workorder_work_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='id_report',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
