# Generated by Django 4.2.23 on 2025-11-12 12:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0041_alter_report_data_alter_report_generated_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassignment',
            name='assigned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
