# Generated by Django 4.2.23 on 2025-11-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repuestos', '0004_stockmovement_purchase_order'),
    ]

    operations = [
    ]
