# Generated by Django 4.2.23 on 2025-11-06 02:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0037_workorder_parts_issued'),
    ]

    operations = [
        migrations.CreateModel(
            name='PauseType',
            fields=[
                ('id_pause_type', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('requires_authorization', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pause_types', to='documents.flotauser')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pause_types', to='documents.flotauser')),
            ],
            options={
                'verbose_name': 'Tipo de Pausa',
                'verbose_name_plural': 'Tipos de Pausa',
                'db_table': 'PauseTypes',
            },
        ),
        migrations.CreateModel(
            name='WorkOrderPause',
            fields=[
                ('id_pause', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_authorization', models.BooleanField(default=False)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('required_quantity', models.IntegerField(blank=True, null=True)),
                ('available_quantity', models.IntegerField(blank=True, null=True)),
                ('affected_spare_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_pauses', to='documents.repuesto')),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_pauses', to='documents.flotauser')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pauses', to='documents.flotauser')),
                ('mechanic_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='documents.workordermechanic')),
                ('pause_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pausas.pausetype')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pauses', to='documents.workorder')),
            ],
            options={
                'verbose_name': 'Pausa de Orden de Trabajo',
                'verbose_name_plural': 'Pausas de Órdenes de Trabajo',
                'db_table': 'WorkOrderPauses',
                'ordering': ['-start_datetime'],
            },
        ),
    ]
